blank_issues_enabled: false   # disable the "Open a blank issue" button

contact_links:
  - name: 💬 Start a Discussion
    url: https://github.com/orgs/EUT-Lab/discussions
    about: Please ask questions, share ideas, or start conversations here.

  - name: 📄 Documentation
    url: https://EUT-Lab.github.io/eut-docs/
    about: Check the docs site for usage, guides, and references.

  - name: 🧾 Citation & Papers
    url: https://doi.org/10.5281/zenodo.17065804
    about: Cite the EUT Core Foundations DOI in your research.
